name: Update package

on:
  push:
    tags:
      - '*'

jobs:
  update-package:
    name: Update package
    runs-on: ubuntu-latest
    steps:
      - id: update-package
        name: Update package
        uses: nedix/actions/update-package@main
        with:
          platforms: linux/amd64,linux/arm64/v8
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
